Ead3::getThumbnail fixes
NatLibFi/RecordManager pull request #103
Opened 2022-02-23 14:49 UTC by LuomaJuha

daogrp no longer exists in Ead3 and dao element can be under did or daoset elements.

2022-02-24 10:17 UTC, EreMaijala requested changes

2022-02-24 10:17 UTC, EreMaijala commented on src/RecordManager/Base/Record/Ead3.php
> +                if (!isset($daoset->dao)) {
Tän tarkistuksen voi jättää pois, kun laittaa alle foreach:iin `$daoset->dao ?? []`

2022-02-24 10:17 UTC, EreMaijala commented on src/RecordManager/Base/Record/Ead3.php
> +            foreach ($root as $daoset) {
Nimeä `$daoset` vaikka `$set`, niin ei hämmennä, kun did ei ole daoset. :)

2022-02-25 08:37 UTC, LuomaJuha commented
@EreMaijala tuunattu!

2022-02-25 09:18 UTC, EreMaijala approved these changes

2022-02-25 09:19 UTC, merged