[ALLI-7731] Refactor Skosmos enrichment.
NatLibFi/RecordManager pull request #121
Opened 2022-12-01 11:24 UTC by EreMaijala

- Makes it possible to filter terms by language.
- Uses JSON-LD records for locally stored entities as well as remotely fetched ones.
- Uses a proper JSON-LD parser.
- Simplifies the local repository import process.
- Unifies topic and geographic id handling across record classes and makes the SkosmosEnrichment base class work as a format-agnostic enrichment.
- Retains backward-compatibility with OnkiLightEnrichment settings.

2022-12-01 11:25 UTC, EreMaijala commented
Note that you can run enrichment without locally stored vocabularies, but it will be slow. To download and import vocabularies, do e.g.:
```
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/allars/data
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/kauno/data
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/koko/data
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/musa/data
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/ysa/data
utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/yso/data

```

2022-12-12 14:26 UTC, LuomaJuha requested changes

2022-12-12 14:26 UTC, LuomaJuha commented on src/RecordManager/Base/Enrichment/SkosmosEnrichment.php
> +        if (!($url = $this->getEntityUrl($id))) {
Should this part check if base_url for SkosmosEnrichment has been set (or if the base_url="database") then just try to search from database? Now if you omit the base_url in hopes of using only the database, then it returns instantly null.

2022-12-13 08:37 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/SkosmosEnrichment.php
> +        if (!($url = $this->getEntityUrl($id))) {
I never thought about that, but makes sense. I'll revise!

2022-12-13 11:47 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/SkosmosEnrichment.php
> +        if (!($url = $this->getEntityUrl($id))) {
Now done.

2022-12-13 14:16 UTC, LuomaJuha approved these changes

2022-12-13 14:17 UTC, merged