[FINNA-491] Ead3 enrich authors from finaf
NatLibFi/RecordManager pull request #141
Opened 2023-07-28 11:59 UTC by LuomaJuha

utils/update_skosmos_data.sh https://api.finto.fi/rest/v1/finaf/data or test with singular records

[SkosmosEnrichment]
url_prefix_whitelist[] = "http://urn.fi/"
uri_prefix_exact_matches[] = "http://urn.fi/URN:NBN:fi:au:finaf:"

2023-08-04 08:17 UTC, EreMaijala requested changes

2023-08-04 08:17 UTC, EreMaijala commented on src/RecordManager/Base/Enrichment/Ead3SkosmosEnrichment.php
> +        'getAuthorIdsForEnrichment' => [
Tässä olisi parempi olla oletuksena getAuthorIds eikä mitään erillistä metodia rikastusta varten.

2023-08-28 07:17 UTC, LuomaJuha commented on src/RecordManager/Base/Enrichment/Ead3SkosmosEnrichment.php
> +        'getAuthorIdsForEnrichment' => [
Jepulis, yritetääs sitä kautta.

2023-08-31 09:34 UTC, EreMaijala approved these changes

2023-08-31 09:34 UTC, merged