[FINNA-1114] Repository locations to geographic places
NatLibFi/RecordManager pull request #146
Opened 2023-10-18 11:50 UTC by siiriylonen

2023-10-18 14:44 UTC, siiriylonen commented
@EreMaijala review, funktio nimen muutin

2023-10-19 07:35 UTC, EreMaijala requested changes

2023-10-19 07:35 UTC, EreMaijala commented on src/RecordManager/Base/Record/Lido.php
> +        $result = array_merge($result, $idPlaces);
Use the spread operator as above instead of array_merge.

2023-10-19 07:55 UTC, EreMaijala commented
@siiriylonen Tests failed, please check!

2023-10-19 10:32 UTC, EreMaijala approved these changes

2023-10-19 10:32 UTC, merged