[FINNA-623] QDC: check for nonproper languages
NatLibFi/RecordManager pull request #153
Opened 2024-02-09 13:26 UTC by LuomaJuha

Very basic way to discard non-proper languages.

2024-02-09 13:34 UTC, EreMaijala requested changes

2024-02-09 13:34 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +                $check = preg_replace(
Olisikohan oikeastaan parempi siirtää kaikki paitsi tuo lexvo-parsiminen Finna-moduulin puolelle? Nyt tässä on vahva oletus sisällöstä, eikä se aina taida pitää paikkaansa.

2024-02-09 13:34 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +                if (mb_strlen($check) > 9 || (!ctype_upper($check) && !ctype_lower($check))) {
Mä sanoisin, että vain ctype_lower pitäisi kelvata. Mappaus ei käsittele isolla kirjoitettuja muutenkaan.

2024-02-09 13:36 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +                    $this->storeWarning("$check suspected to be a nonproper language");
Laita `"unhandled language '$check'"`. Sitten voi periaatteessa löytää kentän alkuosalla kaikki.

2024-02-14 08:13 UTC, LuomaJuha commented on src/RecordManager/Base/Record/Qdc.php
> +                    $this->storeWarning("$check suspected to be a nonproper language");
Ah, totta joo.

2024-02-14 08:14 UTC, LuomaJuha commented on src/RecordManager/Base/Record/Qdc.php
> +                $check = preg_replace(
Jees, voisi olla finna-moduulissa järkevämpi.

2024-02-15 09:21 UTC, LuomaJuha commented
Siirretään finna-moduuliin.

2024-02-15 09:21 UTC, closed without merging