[ALLI-6465] LRMI driver
NatLibFi/RecordManager pull request #51
Opened 2020-09-24 08:20 UTC by samuli

- LRMI-spesifit kentät (educational_*_str_mv) indeksoidaan dynaamisina. Voidaan lisätä skeemaan tarvittaessa.

2020-10-20 13:42 UTC, EreMaijala requested changes
Olisi hyvä fiksata Qdc-luokkaa niin, että kentillä, jotka täällä yliajetaan, on getteri-metodit. Silloin ei tehdä Qdc-luokassa turhaa työtä, joka sitten heitetään menemään täällä. Tällaisia esim. url ja allfields.

2020-10-20 13:42 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lrmi.php
> +        $data['record_format'] = $data['recordtype'] = 'lrmi';
Ota recordtype pois, se poistui äskettäin käytöstä.

2020-10-20 13:42 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lrmi.php
> +        $data['topic']
Nämä mahtuvat yhdelle riville.

2020-10-20 13:42 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lrmi.php
> +        // Reset url to remove thumbnail (from Qdc-driver)
Tää on jännästi tässä language-homman välissä, siirrä vaikka ylemmäs.

2020-10-21 13:22 UTC, samuli commented
- Lisäsin Qdc-ajuriin apumetodeja joita yliajetaan Lrmi:ssä.
- Lrmi:n languages:in käsittely on hieman erilainen koska kielet poimitaan materiaaleista.
- Base/Qdc:n format-kenttä ei nykyisessä versiossa käytä getFormat:ia. Onko tämä tarkoituksella? Muutin käyttämään milloin kenttä voi olla 'Unknown' jos doc->type puuttuu.
- Muutin Lrmi:n allFields-kentien haun käyttämään RecursiveIteratorIteratoria.

2020-10-22 11:27 UTC, EreMaijala requested changes
Vähän ehkä vielä häiritsee se, ettei meillä ole mitään perustoteutusta LRMI-tyypille. Kaikissa muissa formaateissa on Base-luokka myös. Nykyisellä periytymisjärjestyksellä se ei tietenkään ole ihan yksinkertaista, mutta toimisiko niin, että tehdään periminen Base/Qdc -> Base/Lrmi -> Finna/Lrmi? Sitten Finna/Qdc:n toiminallisuus QdcRecordTrait:iin.

2020-10-22 11:27 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> -        $data['record_format'] = 'qdc';
Tän voisi ehkä kuitenkin jättää kovakoodatuksi. Sori!

2020-10-22 11:27 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Lrmi.php
> +        $data['author_facet'] = array_merge($data['author2'], $corporateAuthors);
Jääkö author-kenttä pois author_facetista? Tämäkin olisi parempi tehdä niin, että Base-Qdc -luokassa käytetään esim. getPrimaryAuthors(), getSecondaryAuthors() ja getCorporateAuthors(), jotka yliajetaan täällä. Sitten ei tarvitse tuota facettikenttää asettaa enää erikseen.

2020-10-23 09:26 UTC, samuli commented
Lisäsin Base\Lrmi:n ja siirsin Finna\Qdc:n toiminnot traitiin.

2020-10-26 07:35 UTC, EreMaijala approved these changes

2020-10-26 07:36 UTC, merged