[ALLI-6616] MarcAuth: alternative names
NatLibFi/RecordManager pull request #63
Opened 2021-01-14 10:29 UTC by samuli

- Include indicator b from 100/400/410/500/510.
- Use comma to separate name parts.

2021-01-29 08:21 UTC, EreMaijala approved these changes

2021-01-29 08:22 UTC, EreMaijala requested changes
Tämä pitääkin tehdä Finna-luokkaan. Base-luokka yrittää mallintaa VuFindin indeksoinnin toimintaa.

2021-01-29 08:24 UTC, EreMaijala commented
Tai jos toi vastaa paremmin sitä, mitä VuFindin marc_auth.properties määrittelee, niin sitten eri juttu.

2021-01-29 08:27 UTC, EreMaijala commented
@samuli Vielä lisäkysymys: onko pilkku järkevä erotin? Ainakin 100 a+b tuntuu kummalliselta pilkun kanssa: 
100 0#‡aGustaf‡bV,‡cKing of Sweden,‡d1858-1950
(esimerkki sivulta https://marc21.kansalliskirjasto.fi/aukt/1XX.htm#100)

2021-02-05 09:33 UTC, samuli commented
- Uusi toiminnallisuus siirretty Finnan MarcAuthority-luokkaan.
- Ajateltiin että pilkku olisi paras kompromissi. Nyt käytettävä kauttaviiva ei toimi ^ tuossa esimerkissä ja toisaalta esim. välilyönti ei riitä tässä tapauksessa: https://kansalliskirjasto.finna.fi/AuthorityRecord/melinda.(FI-ASTERI-N)000035903

2021-02-05 15:38 UTC, EreMaijala commented
Ok. Ehkä tuossa voisi harkita sitäkin, että käytetään kentissä jo olevia välimerkkejä, mutta se ei tietenkään toimi, jos ei niitä ole kaikessa aineistossa.

2021-02-05 15:41 UTC, EreMaijala requested changes
trim:n sijaan pitäisi käyttää MetadataUtils::trimTrailingPunctuation, jos on pienikin mahdollisuus, että
a) kentissä on lyhenteitä, jolloin kenttä voi päättyä pisteeseen, jota ei pitäisi poistaa
b) voi olla muitakin välimerkkejä kuin piste (ja toisessa kohdassa pilkku)

2021-02-08 08:05 UTC, samuli commented
Lisäsin myös `getAlternativeNames`:it allfieldsiin.

2021-02-08 11:32 UTC, EreMaijala approved these changes

2021-02-08 11:35 UTC, merged