[ALLI-6904] EAD3: use unitid@label=Tekninen as identifier
NatLibFi/RecordManager pull request #74
Opened 2021-04-07 13:30 UTC by samuli

Käytetään tunnisteena unitid@label=Teknisen identifier-attribuuttia:
```
<unitid label="J&#xE4;rjestysnumero">1</unitid>
    <unitid label="Tekninen" identifier="1710395913"/>
    <unitid label="Analoginen">Cc:25</unitid>
    <unitid label="Viivakoodi">A1572952477rqMQu</unitid>
```

2021-04-09 07:51 UTC, EreMaijala reviewed
Pitäisikö tyypin olla driverParam, jotta sen voisi tarvittaessa konffata datasource-kohtaisesti?

2021-04-13 07:05 UTC, EreMaijala requested changes

2021-04-13 07:05 UTC, EreMaijala commented on src/RecordManager/Finna/Splitter/Ead3.php
> +                        if ($firstId != $this->archiveId) {
Tämän archiveId:n prependauksen voisi tehdä lopuksi, niin ei tartte kahta erillistä kohtaa loopissa.

2021-04-13 07:05 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +        if ($identifier = $this->getUnitId()) {
Haittaako, että tässä oli ennen 'Analoginen' ensisijaisena?

2021-04-13 07:53 UTC, samuli commented on src/RecordManager/Finna/Record/Ead3.php
> +        if ($identifier = $this->getUnitId()) {
En usko, koska Teknisen tulisi toimia tietueen tunnisteena.

2021-04-13 09:23 UTC, EreMaijala commented on src/RecordManager/Finna/Record/Ead3.php
> +        if ($identifier = $this->getUnitId()) {
Ok.

2021-04-13 09:26 UTC, EreMaijala approved these changes

2021-04-13 09:26 UTC, merged