QDC indexing adjustments for ISSNs
NatLibFi/RecordManager pull request #86
Opened 2021-10-12 10:54 UTC by LuomaJuha

Regex is confusing..

2021-10-12 12:07 UTC, EreMaijala requested changes

2021-10-12 12:07 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +            foreach ($this->doc->relation as $rel) {
Tähän ei koskaan päästä ylläolevan isset-tarkistuksen takia. Sen voinee ottaa pois?

2021-10-12 12:07 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +        return array_unique($result);
Turvallisinta laittaa vielä `array_values()` ympärille, muuten voi jäädä reikiä taulukkoon ja tulla kummaa.

2021-10-13 06:38 UTC, LuomaJuha commented on src/RecordManager/Base/Record/Qdc.php
> +            foreach ($this->doc->relation as $rel) {
oho, empty / isset... otin pois

2021-10-15 07:33 UTC, LuomaJuha commented
Mjaha, mutka 500. Pieni säätö

2021-10-15 07:33 UTC, closed without merging