[ALLI-6887] Qdc series to index
NatLibFi/RecordManager pull request #87
Opened 2021-10-20 06:28 UTC by LuomaJuha

2021-10-20 10:45 UTC, EreMaijala requested changes

2021-10-20 10:45 UTC, EreMaijala commented on src/RecordManager/Base/Record/Qdc.php
> +                $result = trim((string)$rel);
Voisi palauttaa suoraan return:lla tästä ja lopussa `return '';` niin ei tartte koko $result-muuttujaa.

2021-10-20 11:02 UTC, LuomaJuha commented on src/RecordManager/Base/Record/Qdc.php
> +                $result = trim((string)$rel);
check

2021-10-20 13:01 UTC, EreMaijala approved these changes

2021-10-20 13:05 UTC, EreMaijala requested changes
@LuomaJuha Nyt hokasin, että nämä taitavat olla ihan kotimaisia käytäntöjä, vai kuinka? Jos näin, niin pitäisi olla Finna/Record/Qdc:ssa.

2021-10-20 13:08 UTC, LuomaJuha commented
@EreMaijala ... niinpä tosiaan. Siirrän ne sinne!

2021-10-20 13:29 UTC, LuomaJuha commented
Laitoin ne QdcRecordTraittiin ku siel on semmonenki lisätty..

2021-10-20 13:31 UTC, EreMaijala commented
@LuomaJuha Olettaen, että se on ok myös LRMI-tietueille, niin hyvä.

2021-10-21 06:49 UTC, LuomaJuha commented
@EreMaijala no, siirsin ne sit ihan varmuuden vuoks finna/qdc puolelle ja tein siihen oman toSolrArrayn et voi vähän pelailla eri tavoin...

2021-10-21 11:54 UTC, EreMaijala commented
@LuomaJuha Sen voi tehdä myös niin, että Base/Qdc:ssä on getSeries, joka ei tee mitään, ja sitten voi yliajaa sen Finna/Qdc:ssa. Silloin kun sitä kutsuu Base:n toSolrArray:ssa, niin ei tartte yliajaa sitä Finnan puolella. Olisiko siistimpi vielä niin?

2021-10-21 12:33 UTC, LuomaJuha commented
@EreMaijala no, sekin... Mie vielä kerran tuunailen :'D

2021-10-22 07:50 UTC, EreMaijala approved these changes

2021-10-22 07:50 UTC, merged